module.exports = {
  content: [
    "./src/pages/Dashboard/**/*.{html,js}",
    "./src/pages/ClienteDetalhe/**/*.{html,js}",
    "./src/pages/Projectos/**/*.{html,js}",
    "./src/shared/**/*.{html,js}"
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b8c3ff",
        primary: "#002b9f",
        outline: "#747686",
        "on-secondary-fixed-variant": "#3b4859",
        "tertiary-container": "#005e2f",
        "on-primary-fixed": "#001356",
        "inverse-primary": "#b8c3ff",
        "secondary-container": "#d6e3f9",
        secondary: "#525f71",
        "surface-dim": "#cddbf0",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#004421",
        "on-error": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#00e17a",
        "tertiary-fixed": "#5fff9b",
        "surface-container": "#e5eeff",
        surface: "#f8f9ff",
        "primary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#00e47c",
        "secondary-fixed-dim": "#bac7dc",
        "on-secondary-fixed": "#0f1c2c",
        "on-primary-fixed-variant": "#0035be",
        "secondary-fixed": "#d6e3f9",
        "on-tertiary-fixed": "#00210d",
        "outline-variant": "#c4c5d7",
        "on-primary-container": "#b6c1ff",
        "primary-container": "#0d3fd1",
        "on-surface-variant": "#444655",
        "surface-tint": "#274fde",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "surface-container-highest": "#d6e3f9",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0f1c2c",
        "surface-variant": "#d6e3f9",
        "on-tertiary-fixed-variant": "#005229",
        "inverse-surface": "#243141",
        "inverse-on-surface": "#eaf1ff",
        "on-background": "#0f1c2c",
        background: "#f8f9ff",
        "on-secondary-container": "#586577",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        inter: ["Arial Rounded MT Bold", "Arial Rounded MT", "Arial", "sans-serif"],
        headline: ["Arial Rounded MT Bold", "Arial Rounded MT", "Arial", "sans-serif"],
        body: ["Arial Rounded MT Bold", "Arial Rounded MT", "Arial", "sans-serif"],
        label: ["Arial Rounded MT Bold", "Arial Rounded MT", "Arial", "sans-serif"],
        display: ["Arial Rounded MT Bold", "Arial Rounded MT", "Arial", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
