module.exports = {
  content: [
    "./src/pages/Dashboard/**/*.{html,js}",
    "./src/pages/ClienteDetalhe/**/*.{html,js}",
    "./src/pages/Projectos/**/*.{html,js}",
    "./src/pages/Users/**/*.{html,js}",
    "./src/pages/auth/**/*.{html,js}",
    "./src/pages/Stock/**/*.{html,js}",
    "./src/pages/Financeiro/**/*.{html,js}",
    "./src/shared/**/*.{html,js}"
  ],
  theme: {
    extend: {
      colors: {
        ink: "#121212",
        action: "#212e3e",
        line: "#d0d0d0",
        "grey-10": "#f2f2f2",
        "grey-20": "#e8e8e8",
        "grey-30": "#dddddd",
        "grey-40": "#d0d0d0",
        "grey-50": "#a3a3a3",
        "grey-60": "#777777",
        "grey-70": "#515151",
        "grey-80": "#383838",
        "grey-90": "#262626",
        "grey-100": "#121212",
        "accent-blue": "#248cd8",
        "accent-blue-light": "#e8f5ff",
        "accent-green": "#10a142",
        "accent-green-light": "#ecfff2",
        "accent-orange": "#f29425",
        "accent-orange-light": "#fff4e8",
        "accent-red": "#ed3237",
        "accent-purple": "#a601ff",
        "accent-purple-light": "#f9efff",
        "primary-fixed-dim": "#b8c3ff",
        primary: "#002b9f",
        outline: "#747686",
        "on-secondary-fixed-variant": "#3b4859",
        "tertiary-container": "#005e2f",
        "on-primary-fixed": "#001356",
        "inverse-primary": "#b8c3ff",
        "secondary-container": "#d6e3f9",
        secondary: "#525f71",
        "surface-dim": "#cddbf0",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#004421",
        "on-error": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#00e17a",
        "tertiary-fixed": "#5fff9b",
        "surface-container": "#e5eeff",
        surface: "#f8f9ff",
        "primary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#00e47c",
        "secondary-fixed-dim": "#bac7dc",
        "on-secondary-fixed": "#0f1c2c",
        "on-primary-fixed-variant": "#0035be",
        "secondary-fixed": "#d6e3f9",
        "on-tertiary-fixed": "#00210d",
        "outline-variant": "#c4c5d7",
        "on-primary-container": "#b6c1ff",
        "primary-container": "#0d3fd1",
        "on-surface-variant": "#444655",
        "surface-tint": "#274fde",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "surface-container-highest": "#d6e3f9",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0f1c2c",
        "surface-variant": "#d6e3f9",
        "on-tertiary-fixed-variant": "#005229",
        "inverse-surface": "#243141",
        "inverse-on-surface": "#eaf1ff",
        "on-background": "#0f1c2c",
        background: "#f8f9ff",
        "on-secondary-container": "#586577",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        none: "0",
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
        control: "10px",
      },
      fontFamily: {
        nunito: ["Nunito", "system-ui", "-apple-system", "sans-serif"],
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        display: ["Outfit", "Inter", "sans-serif"],
        headline: ["Outfit", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
